Repository IMSY-DKFZ/simpa, pull requests merged in 2022-05, with the labels that each got.

#121 Added butterworth bandpass filter
  simpa/core/simulation_modules/reconstruction_module/__init__.py
  simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
  simpa/utils/tags.py
  simpa_tests/automatic_tests/test_bandpass_filter.py
Labels: feature

#141 T139 anisotropy bug
  simpa/core/simulation_modules/optical_simulation_module/optical_forward_model_mcx_adapter.py
  simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
Labels: bug, CRITICAL

#138 Check if key is set before accessing it
  simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
Labels: bug

#137 Rounding fov also in cropping component, fixes #134
  simpa/core/processing_components/monospectral/field_of_view_cropping.py
Labels: bug
