Repository IMSY-DKFZ/simpa, pull requests merged in 2024-06, with the labels that each got.

#270 KWave adapter rotation bug fix
  simpa/core/simulation_modules/acoustic_forward_module/acoustic_forward_module_k_wave_adapter.py
  simpa/core/simulation_modules/reconstruction_module/reconstruction_module_time_reversal_adapter.py
  simpa/visualisation/matplotlib_data_visualisation.py
  simpa_examples/perform_iterative_qPAI_reconstruction.py
  simpa_tests/manual_tests/__init__.py
  simpa_tests/manual_tests/acoustic_forward_models/KWaveAcousticForwardConvenienceFunction.py
  simpa_tests/manual_tests/acoustic_forward_models/MinimalKWaveTest.py
  simpa_tests/manual_tests/processing_components/QPAIReconstruction.py
  simpa_tests/manual_tests/processing_components/TestLinearUnmixingVisual.py
Labels: bug

#310 raise valueerror if interpolated wavelengths are out of range and wri…
  simpa/utils/libraries/spectrum_library.py
Labels: hacking week

#247 Saving norm in a variable named norm_direction_vector_mm
  simpa/core/device_digital_twins/illumination_geometries/slit_illumination.py
Labels: hacktoberfest-accepted

#320 FIX issue with SPIE link check
  .pre-commit-config.yaml
  pre_commit_configs/license_header.txt
  pre_commit_configs/link-config.json
Labels: hacking week

#312 Replace scipy.interp2d by scipy.RegularGridInterpolator
  simpa/utils/deformation_manager.py
  simpa/utils/libraries/structure_library/CircularTubularStructure.py
  simpa/utils/libraries/structure_library/EllipticalTubularStructure.py
  simpa/utils/libraries/structure_library/HorizontalLayerStructure.py
  simpa/utils/tags.py
Labels: hacking week

#315 T314 remove fillers
  simpa/utils/libraries/molecule_library.py
  simpa/utils/libraries/tissue_library.py
Labels: hacking week, optimisation

#306 switch to setuptools
  .github/workflows/pypi.yml
  .readthedocs.yaml
  poetry.lock
  pyproject.toml
Labels: hacking week

#308 Update documentation
  .pre-commit-config.yaml
  README.md
  docs/source/introduction.md
  docs/source/minimal_optical_simulation_uniform_cube.rst
  docs/source/simpa.utils.rst
  docs/source/simpa_examples.rst
Labels: hacking week

#309 Refactored component settings and torch device
  simpa/core/__init__.py
  simpa/core/device_digital_twins/__init__.py
  simpa/core/device_digital_twins/detection_geometries/__init__.py
  simpa/core/device_digital_twins/detection_geometries/detection_geometry_base.py
  simpa/core/device_digital_twins/digital_device_twin_base.py
  simpa/core/device_digital_twins/illumination_geometries/__init__.py
  simpa/core/device_digital_twins/illumination_geometries/illumination_geometry_base.py
  simpa/core/device_digital_twins/illumination_geometries/ithera_msot_invision_illumination.py
  simpa/core/device_digital_twins/illumination_geometries/pencil_array_illumination.py
  simpa/core/device_digital_twins/illumination_geometries/slit_illumination.py
  simpa/core/device_digital_twins/pa_devices/__init__.py
  simpa/core/device_digital_twins/pa_devices/ithera_msot_acuity.py
  simpa/core/processing_components/__init__.py
  simpa/core/simulation.py
  simpa/core/simulation_modules/__init__.py
  simpa/core/simulation_modules/acoustic_forward_module/__init__.py
  simpa/core/simulation_modules/optical_simulation_module/__init__.py
  simpa/core/simulation_modules/optical_simulation_module/optical_forward_model_mcx_adapter.py
  simpa/core/simulation_modules/reconstruction_module/__init__.py
  simpa/core/simulation_modules/volume_creation_module/__init__.py
  simpa/utils/calculate.py
  simpa_tests/automatic_tests/device_tests/test_field_of_view.py
  simpa_tests/automatic_tests/test_equal.py
Labels: hacking week

#328 fix tests
  MANIFEST.in
  simpa_tests/__init__.py
  simpa_tests/automatic_tests/device_tests/test_field_of_view.py
  simpa_tests/automatic_tests/test_bandpass_filter.py
  simpa_tests/automatic_tests/test_device_UUID.py
  simpa_tests/do_coverage.py
Labels: hacking week

#331 Disabled autopep8 formatting of relative import lines
  simpa/core/device_digital_twins/__init__.py
Labels: hacking week
