Repository IMSY-DKFZ/simpa, pull requests merged in 2024-07, with the labels that each got.

#321 T180 refactoring tissue lib
  docs/source/simpa.core.device_digital_twins.detection_geometries.rst
  docs/source/simpa.core.device_digital_twins.illumination_geometries.rst
  docs/source/simpa.core.device_digital_twins.rst
  docs/source/simpa_examples.rst
  simpa/utils/libraries/tissue_library.py
Labels: documentation, feature, hacking week

#293 + RingIlluminationGeometry
  docs/source/simpa.core.device_digital_twins.illumination_geometries.rst
  docs/source/simpa_examples.rst
  simpa/core/device_digital_twins/__init__.py
  simpa/core/device_digital_twins/illumination_geometries/ring_illumination.py
  simpa/utils/tags.py
  simpa_tests/automatic_tests/device_tests/test_ring_illumination.py
  simpa_tests/automatic_tests/test_io_handling.py
Labels: hacking week

#340 T339 specific hetero
  simpa/core/device_digital_twins/pa_devices/ithera_msot_acuity.py
  simpa/utils/libraries/molecule_library.py
  simpa/utils/libraries/structure_library/HorizontalLayerStructure.py
  simpa/utils/libraries/structure_library/StructureBase.py
  simpa/utils/libraries/structure_library/__init__.py
  simpa_examples/minimal_optical_simulation_heterogeneous_tissue.py
Labels: feature

#313 T300 benchmarking
  .gitignore
  CONTRIBUTING.md
  README.md
  docs/source/bench_link.md
  docs/source/benchmarking.md
  docs/source/images/benchmarking_table.png
  docs/source/index.rst
  pyproject.toml
  simpa/core/__init__.py
  simpa/core/processing_components/__init__.py
  simpa/core/simulation_modules/__init__.py
  simpa/core/simulation_modules/acoustic_forward_module/__init__.py
  simpa/core/simulation_modules/reconstruction_module/__init__.py
  simpa/core/simulation_modules/volume_creation_module/__init__.py
  simpa/utils/deformation_manager.py
  simpa/utils/profiling.py
  simpa_examples/__init__.py
  simpa_examples/benchmarking/__init__.py
  simpa_examples/benchmarking/extract_benchmarking_data.py
  simpa_examples/benchmarking/get_final_table.py
  simpa_examples/benchmarking/performance_check.py
  simpa_examples/benchmarking/run_benchmarking.sh
  simpa_examples/linear_unmixing.py
  simpa_examples/minimal_optical_simulation.py
  simpa_examples/minimal_optical_simulation_uniform_cube.py
  simpa_examples/msot_invision_simulation.py
  simpa_examples/optical_and_acoustic_simulation.py
  simpa_examples/perform_image_reconstruction.py
  simpa_examples/perform_iterative_qPAI_reconstruction.py
  simpa_examples/segmentation_loader.py
  simpa_tests/automatic_tests/device_tests/test_field_of_view.py
  simpa_tests/automatic_tests/test_bandpass_filter.py
  simpa_tests/do_coverage.py
  simpa_tests/manual_tests/acoustic_forward_models/KWaveAcousticForwardConvenienceFunction.py
Labels: feature, hacking week, optimisation

#325 Add installed simpa version in hdf5 files
  simpa/__init__.py
  simpa/core/simulation.py
  simpa/io_handling/io_hdf5.py
  simpa/utils/dict_path_manager.py
  simpa/utils/tags.py
Labels: hacking week

#311 Additional executable flags
  simpa/core/simulation_modules/__init__.py
  simpa/core/simulation_modules/acoustic_forward_module/acoustic_forward_module_k_wave_adapter.py
  simpa/core/simulation_modules/optical_simulation_module/optical_forward_model_mcx_adapter.py
  simpa/core/simulation_modules/optical_simulation_module/optical_forward_model_mcx_reflectance_adapter.py
  simpa/core/simulation_modules/reconstruction_module/reconstruction_module_time_reversal_adapter.py
  simpa/utils/matlab.py
  simpa/utils/tags.py
  simpa_examples/optical_and_acoustic_simulation.py
  simpa_tests/automatic_tests/test_additional_flags.py
  simpa_tests/manual_tests/executables/MATLABAdditionalFlags.py
  simpa_tests/manual_tests/executables/MCXAdditionalFlags.py
Labels: hacking week

#318 T105 overview manual test
  .gitignore
  README.md
  pyproject.toml
  simpa_tests/manual_tests/digital_device_twins/VisualiseDevices.py
  simpa_tests/manual_tests/generate_overview.py
  simpa_tests/manual_tests/optical_forward_models/ComputeDiffuseReflectance.py
  simpa_tests/manual_tests/test_with_experimental_measurements/ReproduceDISMeasurements.py
Labels: hacking week

#182 T115 include bvf
  simpa/utils/calculate.py
  simpa/utils/constants.py
  simpa/utils/libraries/molecule_library.py
  simpa/utils/tags.py
  simpa_tests/automatic_tests/test_calculation_utils.py
  simpa_tests/automatic_tests/tissue_library/test_core_assumptions.py
  simpa_tests/test_utils/tissue_composition_tests.py
Labels: hacking week

#368 T367 plot bvf
  simpa/visualisation/matplotlib_data_visualisation.py
Labels: feature
